name: '🚀 Publish Plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/publish.yaml@master
    with:
      version: ${{ github.event.release.tag_name }}
      is-unstable: ${{ github.event.release.prerelease }}
    secrets:
      deploy-host: ${{ secrets.DEPLOY_HOST }}
      deploy-user: ${{ secrets.DEPLOY_USER }}
      deploy-key: ${{ secrets.DEPLOY_KEY }}
  publishOnRelease:
    needs:
      - upload
    runs-on: ubuntu-latest
    env:
      GITHUB_RELEASE: "https://github.com/chenqiaoanying/jellyfin-plugin-javscraper/releases/download"
    steps:
      - name: Create Plugin Manifest
        run: |
          env
          jprm --verbosity=debug repo init .
          jprm --verbosity=debug repo add --url=xyz . ./*.zip
          URL="$GITHUB_RELEASE/${{ github.event.release.tag_name }}/"
          URL=$(echo $url|sed -r 's/([\$\.\*\/\[\\^])/\\\1/g'| sed 's/[]]/\[]]/g')
          sed "s/\"sourceUrl\".*\//\"sourceUrl\": \"$url/" manifest.json
      - name: Upload GH Release Assets
        uses: shogo82148/actions-upload-release-asset@8dbaa4469aa7256e70624d72f2567fac8f5341b3
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./manifest.json
